Repository ThugMS/GameLab_W03, pull requests merged in 2023-08, with the labels that each got.

#2 [Feat] : 플레이어 카메라 회전 구현 완료 회전과 움직임 구현
  Assets/InputSystem.meta
  Assets/InputSystem/Player.inputactions
  Assets/InputSystem/Player.inputactions.meta
  Assets/Materials.meta
  Assets/Materials/Black.mat
  Assets/Materials/Black.mat.meta
  Assets/Prefabs/Managers.meta
  Assets/Prefabs/Managers/InputManager.prefab
  Assets/Prefabs/Managers/InputManager.prefab.meta
  Assets/Scenes/MSTest.unity
  Assets/Scenes/MSTest.unity.meta
  Assets/Scripts/MS/FollowTransform.cs
  Assets/Scripts/MS/FollowTransform.cs.meta
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Player.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TagManager.asset
Labels: minseok, Feat

#4 [Feat] : Player 카메라 프리팹 추가
  Assets/InputSystem.inputsettings.asset
  Assets/InputSystem.inputsettings.asset.meta
  Assets/InputSystem/Player.inputactions
  Assets/Prefabs/CameraSet.prefab
  Assets/Prefabs/CameraSet.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/MSTest.unity
  Assets/Scripts/MS/Baby.cs
  Assets/Scripts/MS/Baby.cs.meta
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Youth.cs
  Assets/Scripts/MS/Youth.cs.meta
  ProjectSettings/TagManager.asset
Labels: minseok, Feat

#5 [Fix] : 움직임 수정
  Assets/InputSystem.inputsettings.asset
  Assets/Scenes/MSTest.unity
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: minseok, Fix

#6 [Fix] : Input System Manager 수정
  Assets/InputSystem/Character.inputactions
  Assets/InputSystem/Character.inputactions.meta
  Assets/InputSystem/PlayerSub.inputactions
  Assets/InputSystem/PlayerSub.inputactions.meta
  Assets/Prefabs/Managers/InputManager.prefab
  Assets/Scenes/MSTest.unity
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Fix

#8 [Feat] : input Action 시간 조절 키 추가
  Assets/InputSystem/PlayerSub.inputactions
Labels: minseok, Feat

#9 Mk
  Assets/Prefabs/Ax.prefab
  Assets/Prefabs/Ax.prefab.meta
  Assets/Prefabs/Switch.prefab
  Assets/Prefabs/Switch.prefab.meta
  Assets/Scenes/MK.unity
  Assets/Scenes/MK.unity.meta
  Assets/Scripts/MK/Ax.cs
  Assets/Scripts/MK/Ax.cs.meta
  Assets/Scripts/MK/ISwitchConnectedObjects.cs
  Assets/Scripts/MK/ISwitchConnectedObjects.cs.meta
  Assets/Scripts/MK/Switch.meta
  Assets/Scripts/MK/Switch/InteractSwitch.cs
  Assets/Scripts/MK/Switch/InteractSwitch.cs.meta
  Assets/Scripts/MK/Switch/Switch.cs
  Assets/Scripts/MK/Switch/Switch.cs.meta
  ProjectSettings/TagManager.asset
Labels: MK, Feat

#11 [Feat] : 점프 구현
  Assets/InputSystem/PlayerSub.inputactions
  Assets/Scenes/MSTest.unity
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Youth.cs
  ProjectSettings/DynamicsManager.asset
Labels: minseok, Feat

#13 [Feat] : 도끼 쥐고 놓는 액션 추가
  Assets/Materials/Wood.mat
  Assets/Materials/Wood.mat.meta
  Assets/Prefabs/Ax.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/MSTest.unity
  Assets/Scripts/MK/Switch/InteractSwitch.cs
  Assets/Scripts/MK/Switch/Switch.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Senior.cs.meta
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Feat

#15 [Feat] : 감도 설정 추가
  Assets/Prefabs/Ax.prefab
  Assets/SM/Prefabs/DebugTree.prefab
  Assets/Scenes/MSTest.unity
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/PlayerManager.cs
  Assets/Scripts/MS/PlayerManager.cs.meta
  Assets/Scripts/MS/Youth.cs
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/TagManager.asset
Labels: minseok, Feat

#16 Sm
  Assets/Prefabs/Managers/InputManager.prefab
  Assets/Prefabs/Player.prefab
  Assets/SM/Prefabs/DebugIce.prefab
  Assets/SM/Prefabs/DebugTree.prefab
  Assets/SM/Prefabs/SceneManager.prefab
  Assets/SM/Prefabs/SceneManager.prefab.meta
  Assets/SM/Scenes/SM_Test.unity
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/SM/Scenes/SM_Tutorial.unity.meta
  Assets/SM/Scripts/LoadSceneManager.cs
  Assets/SM/Scripts/LoadSceneManager.cs.meta
  Assets/SM/Scripts/SizeChangeByTime.cs
  Assets/SM/Scripts/Tree.cs
  Assets/Scripts/MS/Switch.meta
  Assets/Scripts/MS/Switch/InteractSwitch.cs
  Assets/Scripts/MS/Switch/InteractSwitch.cs.meta
  Assets/Scripts/MS/Switch/Switch.cs
  Assets/Scripts/MS/Switch/Switch.cs.meta
Labels: SM, Feat, Fix

#18 Minseok
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Youth.cs
  ProjectSettings/DynamicsManager.asset
Labels: minseok, Feat

#20 [Feat] : 플레이어 도끼 수정
  Assets/Prefabs/Player.prefab
  Assets/Scripts/MS/PlayerManager.cs
Labels: minseok, Feat

#21 [Feat] : 플레이어 시간변화 구현
  Assets/Prefabs/Player 1.prefab
  Assets/Prefabs/Player 1.prefab.meta
  Assets/Scenes/MSTest.unity
  Assets/Scripts/MS/PlayerManager.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Feat

#30 [Feat] : 열쇠를 지고 상태가 바뀌도록 구현
  Assets/SM/Scripts/TimeManager.cs
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/PlayerManager.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Feat, Fix

#31 [Fix] : 게임 시작시 시간에 맞게 외형 변화하게 수정
  Assets/SM/Scripts/TimeManager.cs
  Assets/Scripts/MS/PlayerManager.cs
Labels: minseok, Fix

#35 [Feat] : 애니메이션 추가
  Assets/Animations/Baby.controller
  Assets/Animations/Baby.controller.meta
  Assets/Animations/BabyIdle.anim
  Assets/Animations/BabyIdle.anim.meta
  Assets/Animations/Senior.controller
  Assets/Animations/Senior.controller.meta
  Assets/Animations/SeniorIdle.anim
  Assets/Animations/SeniorIdle.anim.meta
  Assets/Animations/SeniorKey.anim
  Assets/Animations/SeniorKey.anim.meta
  Assets/Animations/Youth.controller
  Assets/Animations/Youth.controller.meta
  Assets/Animations/YouthAxe.anim
  Assets/Animations/YouthAxe.anim.meta
  Assets/Animations/YouthIdle.anim
  Assets/Animations/YouthIdle.anim.meta
  Assets/Animations/YouthKey.anim
  Assets/Animations/YouthKey.anim.meta
  Assets/KeyAnimation.cs
  Assets/KeyAnimation.cs.meta
  Assets/Prefabs/Player 1.prefab
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scripts/MS/Baby.cs
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Feat

#37 [Fix] : 애니메이션 수정, 물건 떨어지는 위치 수정
  Assets/Animations/Senior.controller
  Assets/Animations/SeniorIdel.anim
  Assets/Animations/SeniorIdel.anim.meta
  Assets/Animations/Youth 1.controller
  Assets/Animations/Youth 1.controller.meta
  Assets/KeySeniorAnimation.cs
  Assets/KeySeniorAnimation.cs.meta
  Assets/Prefabs/Player 1.prefab
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Switch/Switch.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Fix

#40 [Feat] : 카메라 쉐이크 추가
  Assets/Prefabs/CameraSet.prefab
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scripts/MS/CameraShakeTrigger.cs
  Assets/Scripts/MS/CameraShakeTrigger.cs.meta
Labels: minseok, Feat

#41 Sm
  Assets/Models/Game Assets/TreeBody.fbx
  Assets/Models/Game Assets/TreeBody.fbx.meta
  Assets/Models/Game Assets/TreeHead.fbx
  Assets/Models/Game Assets/TreeHead.fbx.meta
  Assets/Prefabs/Tree/Tree pine.fbx
  Assets/Prefabs/Tree/Tree pine.fbx.meta
  Assets/SM/Prefabs/Tree.prefab
  Assets/SM/Prefabs/Tree.prefab.meta
  Assets/SM/Scenes/SM_Level_1.unity
  Assets/SM/Scenes/SM_Test.unity
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/SM/Scripts/Level1Door.cs
  Assets/SM/Scripts/Level1Door.cs.meta
  Assets/SM/Scripts/TimeInfluenced.cs
  Assets/SM/Scripts/TimeManager.cs
  Assets/SM/Scripts/TreeChangeByTime.cs
  Assets/SM/Scripts/TreeChangeByTime.cs.meta
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Switch/Switch.cs
  Assets/Scripts/MS/Youth.cs
Labels: SM, Feat, Fix

#42 [Feat] : 시간 정지 행동정지 스크립트 구현
  Assets/3rd/castle_assets_package/Prefabs/Gate.prefab
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/PlayerManager.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Feat

#43 [Fix] 튜토 수정
  Assets/Materials/Terrain.mat
  Assets/Materials/Terrain.mat.meta
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/SM/Scripts/TreeChangeByTime.cs
Labels: MK, Feat, Fix

#47 [Fix] : 충돌판저 수정
  Assets/Scenes/Stage2.unity
  Assets/Scenes/Stage2.unity.meta
  Assets/Scripts/MS/Baby.cs
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/PlayerManager.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Fix

#48 [Feat] : Stage 2 개발
  Assets/Scenes/Stage2.unity
  Assets/Scripts/MS/Senior.cs
Labels: minseok, Feat

#52 [Fix] : 게임 오브젝트 destroy 에러 수정
  Assets/InputSystem/PlayerSub.inputactions
  Assets/Materials/ZeroFriction.physicMaterial
  Assets/Materials/ZeroFriction.physicMaterial.meta
  Assets/Prefabs/Panel.prefab
  Assets/Prefabs/Panel.prefab.meta
  Assets/Prefabs/UIManager.prefab
  Assets/Prefabs/UIManager.prefab.meta
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/SM/Scripts/IceChangeByTime.cs
  Assets/Scenes/Stage2.unity
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/UIManager.cs
  Assets/Scripts/MS/UIManager.cs.meta
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Fix

#53 Minseok
  Assets/SM/Scripts/IceChangeByTime.cs
Labels: minseok, Fix

#54 [Feat] : 마지막 빌드
  Assets/Animations/BabyIdle.anim
  Assets/Animations/YouthIdle.anim
  Assets/Prefabs/Player 1.prefab
  Assets/SM/Scenes/End.unity
  Assets/SM/Scenes/End.unity.meta
  Assets/SM/Scenes/SM_Level_1.unity
  Assets/SM/Scenes/SM_Level_3.unity
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scenes/Stage2.unity
  Assets/Scenes/Title.unity
  Assets/Scenes/Title.unity.meta
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/PlayerManager.cs
  Assets/Scripts/MS/UIManager.cs
  Assets/Scripts/MS/Youth.cs
  Assets/TitleCanvas.cs
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: minseok, MK, SM, Feat
