Repository ThugMS/GameLab_W03, pull requests merged in 2023-09, with the labels that each got.

#56 Sm
  Assets/SM/Materials/SwitchConnected.mat
  Assets/SM/Materials/SwitchConnected.mat.meta
  Assets/SM/Scenes/SM_Level_1.unity
  Assets/SM/Scenes/SM_Test.unity
  Assets/SM/Scripts/Level1Door.cs
  Assets/Scenes/Stage2.unity
  Assets/Scripts/MS/Player.cs
Labels: SM, Fix

#57 [Feat] : 스위치 눌렀을 때 반응 추가
  Assets/Animations/Switch.controller
  Assets/Animations/Switch.controller.meta
  Assets/Animations/SwitchPress.anim
  Assets/Animations/SwitchPress.anim.meta
  Assets/Prefabs/SwitchObject/Switch.prefab
  Assets/Scenes/Stage2.unity
  Assets/Scripts/MS/Switch/Switch.cs
Labels: minseok, Feat

#58 [Fix]: 시간 바뀔 때 이동 정지 코드 수정
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/PlayerManager.cs
Labels: minseok, Fix

#59 [Fix] : 조작감개선
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Fix

#62 [Fix] : 조작감 움직임 개선
  Assets/Scripts/MS/Player.cs
Labels: minseok, Fix

#65 [Feat] : 떨어지는 플랫폼 개발 완료
  Assets/Scenes/Stage2.unity
  Assets/Scripts/MS/FallingObject.cs
  Assets/Scripts/MS/FallingObject.cs.meta
Labels: minseok, Feat

#68 [Fix] 튜토씬, 문/스위치 프리펩 수정
  Assets/3rd/PolygonStarter/Materials/PolygonStarter_Mat_01.mat
  Assets/3rd/castle_assets_package/Prefabs/Gate.prefab
  Assets/Prefabs/SwitchObject/Switch.prefab
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scripts/MK/Door.cs
Labels: MK, Fix

#69 [Fix] : 시간 바뀌지않는 오류 수정
  Assets/Animations/Youth.controller
  Assets/Animations/YouthDead.anim
  Assets/Animations/YouthDead.anim.meta
  Assets/DeadAnimation.cs
  Assets/DeadAnimation.cs.meta
  Assets/Prefabs/Player 1.prefab
  Assets/SM/Scripts/PlayerControlTime.cs
  Assets/Scenes/Stage2.unity
  Assets/Scripts/MS/FallingObject.cs
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, Fix

#70 [Fix] : 스테이지2 수정
  Assets/Scenes/Stage2.unity
Labels: minseok, Fix

#71 Update SM_Tutorial.unity
  Assets/SM/Scenes/SM_Tutorial.unity
Labels: MK, Fix

#72 [Feat] : 점프 조금 더 부드럽고 판정을 후하게 줌
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scripts/MS/Player.cs
Labels: minseok, Feat, Fix

#73 [Feat] : 죽는 애니메이션 추가
  Assets/Animations/Youth.controller
  Assets/Animations/YouthDead.anim
  Assets/DeadAnimation.cs
  Assets/Prefabs/Player 1.prefab
  Assets/SM/Materials/Skin.mat
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/PlayerManager.cs
Labels: minseok, Feat

#81 [Feat] : 떨어지는 오브젝트 확장성 구현
  Assets/Animations/Baby.controller
  Assets/KeyAnimation.cs
  Assets/Prefabs/FaillingObj.prefab
  Assets/Prefabs/FaillingObj.prefab.meta
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scripts/MS/FallingObject.cs
Labels: minseok, Feat

#82 [Feat] : 죽는 모션 모두 추가
  Assets/Animations/Baby.controller
  Assets/Animations/BabyDead.anim
  Assets/Animations/BabyDead.anim.meta
  Assets/Animations/SeniorDead.anim
  Assets/Animations/SeniorDead.anim.meta
  Assets/Animations/Youth 1.controller
  Assets/Prefabs/Player 1.prefab
  Assets/SM/Scripts/TreeChangeByTime.cs
  Assets/Scripts/MS/FallingObject.cs
  Assets/Scripts/MS/Player.cs
Labels: minseok, Feat

#84 [Feat] ice, tree 색 바뀌기
  Assets/SM/Prefabs/Ice.prefab
  Assets/SM/Scripts/IceChangeByTime.cs
  Assets/SM/Scripts/TreeChangeByTime.cs
Labels: MK, Feat

#85 [Feat] : 떨어지는 오브젝트 모양 추가
  Assets/Prefabs/FaillingObj.prefab
  Assets/SM/Scenes/SM_Tutorial.unity
Labels: minseok, Feat

#86 [Fix] : 나무 투명효과 수정, 튜토씬 수정
  Assets/Models/Game Assets/Leaf green.mat
  Assets/SM/Scenes/SM_Tutorial.unity
Labels: minseok, MK, Fix

#87 [Feat] 눈 머티리얼, 오브젝트 매니저 동적 추가
  Assets/Materials/Ice.mat
  Assets/SM/Scripts/IceChangeByTime.cs
  Assets/SM/Scripts/ObjectManager.cs
  Assets/SM/Scripts/TimeInfluenced.cs
  Assets/SM/Scripts/TimeManager.cs
  Assets/SM/Scripts/TreeChangeByTime.cs
Labels: minseok, MK, SM, Feat, Fix

#88 Sm
  Assets/SM/Scenes/SM_Level_4.unity
  Assets/SM/Scripts/Fire.cs
  Assets/SM/Scripts/FireOrigin.cs
  Assets/SM/Scripts/IceChangeByTime.cs
  Assets/SM/Scripts/TimeManager.cs
  Assets/SM/Scripts/TorchLight.cs
  Assets/SM/Scripts/TreeChangeByTime.cs
Labels: SM, Fix

#89 Update SM_Level_1.unity
  Assets/SM/Scenes/SM_Level_1.unity
Labels: MK, Fix

#90 Update SM_Level_1.unity
  Assets/SM/Scenes/SM_Level_1.unity
Labels: MK, Fix

#91 [Fix] : 노인 불에 죽는모션 수정
  Assets/SM/Scenes/SM_Test.unity
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/SM/Scripts/Fire.cs
  Assets/Scripts/MS/FallingObject.cs
  Assets/Scripts/MS/Player.cs
  Assets/Scripts/MS/Senior.cs
  Assets/Scripts/MS/Youth.cs
Labels: minseok, MK, SM, Fix

#93 [Feat] : Fire 이펙트 추가
  Assets/Low Poly Fire.meta
  Assets/Low Poly Fire/Documentation - TOON FIRE.pdf
  Assets/Low Poly Fire/Documentation - TOON FIRE.pdf.meta
  Assets/Low Poly Fire/Materials.meta
  Assets/Low Poly Fire/Materials/Demo Skybox.mat
  Assets/Low Poly Fire/Materials/Demo Skybox.mat.meta
  Assets/Low Poly Fire/Materials/Fire Wood.mat
  Assets/Low Poly Fire/Materials/Fire Wood.mat.meta
  Assets/Low Poly Fire/Materials/FireMaterial.mat
  Assets/Low Poly Fire/Materials/FireMaterial.mat.meta
  Assets/Low Poly Fire/Models.meta
  Assets/Low Poly Fire/Models/FireWood.fbx
  Assets/Low Poly Fire/Models/FireWood.fbx.meta
  Assets/Low Poly Fire/Prefabs.meta
  Assets/Low Poly Fire/Prefabs/Pink-FireWood.prefab
  Assets/Low Poly Fire/Prefabs/Pink-FireWood.prefab.meta
  Assets/Prefabs/Fire_Pink.prefab
  Assets/Prefabs/Fire_Pink.prefab.meta
  Assets/SM/Prefabs/Fire.prefab
Labels: minseok, Feat

#94 [Fix] : 토치 수정
  Assets/SM/Prefabs/Torch.prefab
Labels: minseok, Fix

#95 [Feat] : 움직이는 플랫폼 부드럽게 움직이게 추가
  Assets/Prefabs/FloorObj.prefab
  Assets/Prefabs/FloorObj.prefab.meta
  Assets/Scenes/Stage5.unity
  Assets/Scenes/Stage5.unity.meta
  Assets/Scripts/MS/FallingObject.cs
  Assets/Scripts/MS/Player.cs
Labels: minseok, Feat

#97 [Feat] : 공중에 있을 시 시간변경 불가능
  Assets/SM/Scripts/PlayerControlTime.cs
  Assets/Scenes/Stage5.unity
  Assets/Scripts/MS/Player.cs
Labels: minseok, Feat

#100 [Add] 씬1 스위치 진동 추가 *100번째 감사합니다*
  Assets/SM/Scenes/SM_Level_1.unity
  Assets/SM/Scripts/Level1Door.cs
Labels: minseok, MK, Feat

#101 [Feat] : 커서 안보이게 수정해버리기
  Assets/Prefabs/UISet.prefab
  Assets/Prefabs/UISet.prefab.meta
  Assets/Scenes/Stage4 (copy).unity
  Assets/Scripts/MS/UIManager.cs
Labels: minseok, Feat

#103 [Feat] : 움직이는 플랫폼 offset을 추가해서 캐릭터가 들어가지않게 설정
  Assets/Prefabs/FaillingObj.prefab
  Assets/Scenes/Stage4 (copy).unity
  Assets/Scripts/MS/FallingObject.cs
Labels: minseok, Feat

#106 [Fix] : 불 설치하는 발판 계산식 수정, 떠오르는 플랫폼 수정완료
  Assets/Prefabs/FaillingObj.prefab
  Assets/SM/Scenes/SM_Level_5.unity
  Assets/SM/Scripts/TorchLight.cs
  Assets/Scenes/Stage4 (copy).unity
  Assets/Scripts/MS/Player.cs
Labels: minseok, Fix

#110 [Feat] : ESC 메뉴일때는 시간변동 못하게 추가
  Assets/SM/Scripts/PlayerControlTime.cs
  Assets/Scripts/MS/UIManager.cs
Labels: minseok, Feat

#112 [Feat] 씬2
  Assets/SM/Scenes/Stage2_Test.unity
  Assets/SM/Scenes/Stage2_Test.unity.meta
  Assets/Scenes/Ax (1).prefab
  Assets/Scenes/Ax (1).prefab.meta
  Assets/Scenes/CameraSet.prefab
  Assets/Scenes/CameraSet.prefab.meta
  Assets/Scenes/Directional Light.prefab
  Assets/Scenes/Directional Light.prefab.meta
  Assets/Scenes/EventSystem.prefab
  Assets/Scenes/EventSystem.prefab.meta
  Assets/Scenes/FaillingObj.prefab
  Assets/Scenes/FaillingObj.prefab.meta
  Assets/Scenes/Gate.prefab
  Assets/Scenes/Gate.prefab.meta
  Assets/Scenes/Main Camera.prefab
  Assets/Scenes/Main Camera.prefab.meta
  Assets/Scenes/Managers.prefab
  Assets/Scenes/Managers.prefab.meta
  Assets/Scenes/Map.prefab
  Assets/Scenes/Map.prefab.meta
  Assets/Scenes/Player 1.prefab
  Assets/Scenes/Player 1.prefab.meta
  Assets/Scenes/Stage2.unity
  Assets/Scenes/Stage2_Test.unity
  Assets/Scenes/Switch.prefab
  Assets/Scenes/Switch.prefab.meta
  Assets/Scenes/TimeInfluencedObject.prefab
  Assets/Scenes/TimeInfluencedObject.prefab.meta
  Assets/Sprite/bigtreepic 1.png
  Assets/Sprite/bigtreepic 1.png.meta
  Assets/Sprite/bigtreepic.png
  Assets/Sprite/bigtreepic.png.meta
  Assets/Sprite/dokki.png
  Assets/Sprite/dokki.png.meta
  Assets/Sprite/smalltreepic.png
  Assets/Sprite/smalltreepic.png.meta
  Assets/Sprite/treepic 1.png
  Assets/Sprite/treepic 1.png.meta
  Assets/Sprite/treepic.png
  Assets/Sprite/treepic.png.meta
Labels: MK, Feat

#114 [Feat] : 빌드 파일
  Assets/Prefabs/FireLight.prefab
  Assets/Prefabs/FireLight.prefab.meta
  Assets/Prefabs/Fire_Pink.prefab
  Assets/SM/Scenes/Level3.lighting
  Assets/SM/Scenes/Level3.lighting.meta
  Assets/SM/Scenes/Level5.lighting
  Assets/SM/Scenes/Level5.lighting.meta
  Assets/SM/Scenes/New Lighting Settings.lighting
  Assets/SM/Scenes/New Lighting Settings.lighting.meta
  Assets/SM/Scenes/SM_Level_1.meta
  Assets/SM/Scenes/SM_Level_1.unity
  Assets/SM/Scenes/SM_Level_1/LightingData.asset
  Assets/SM/Scenes/SM_Level_1/LightingData.asset.meta
  Assets/SM/Scenes/SM_Level_1/ReflectionProbe-0.exr
  Assets/SM/Scenes/SM_Level_1/ReflectionProbe-0.exr.meta
  Assets/SM/Scenes/SM_Level_3.meta
  Assets/SM/Scenes/SM_Level_3.unity
  Assets/SM/Scenes/SM_Level_3/LightingData.asset
  Assets/SM/Scenes/SM_Level_3/LightingData.asset.meta
  Assets/SM/Scenes/SM_Level_3/ReflectionProbe-0.exr
  Assets/SM/Scenes/SM_Level_3/ReflectionProbe-0.exr.meta
  Assets/SM/Scenes/SM_Level_5.meta
  Assets/SM/Scenes/SM_Level_5.unity
  Assets/SM/Scenes/SM_Level_5/LightingData.asset
  Assets/SM/Scenes/SM_Level_5/LightingData.asset.meta
  Assets/SM/Scenes/SM_Level_5/ReflectionProbe-0.exr
  Assets/SM/Scenes/SM_Level_5/ReflectionProbe-0.exr.meta
  Assets/SM/Scenes/SM_Tutorial.unity
  Assets/Scenes/Level2.lighting
  Assets/Scenes/Level2.lighting.meta
  Assets/Scenes/Level4.lighting
  Assets/Scenes/Level4.lighting.meta
  Assets/Scenes/Stage2.meta
  Assets/Scenes/Stage2.unity
  Assets/Scenes/Stage2/LightingData.asset
  Assets/Scenes/Stage2/LightingData.asset.meta
  Assets/Scenes/Stage2/ReflectionProbe-0.exr
  Assets/Scenes/Stage2/ReflectionProbe-0.exr.meta
  Assets/Scenes/Stage4.meta
  Assets/Scenes/Stage4.unity
  Assets/Scenes/Stage4/LightingData.asset
  Assets/Scenes/Stage4/LightingData.asset.meta
  Assets/Scenes/Stage4/ReflectionProbe-0.exr
  Assets/Scenes/Stage4/ReflectionProbe-0.exr.meta
  Assets/TitleCanvas.cs
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: minseok, Feat

#115 [Feat] : 진짜 빌드이기를 빕니다.
  Assets/SM/Scenes/SM_Level_3.unity
  Assets/Scenes/Stage2.unity
Labels: minseok, Feat

#117 [Feat] : 커밋
  Assets/NewBehaviourScript.cs
  Assets/NewBehaviourScript.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: minseok, Feat
